name: CI

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
    - master
    - releases/*

  pull_request:
    branches:
    - master

jobs:
  ubuntu:
    name: Ubuntu native build (x86-64)
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: >-
           sudo apt-get install -y --no-install-recommends g++ meson
           ninja-build python3 python3-pip pkgconf libedit-dev libpcre2-dev
           libssl-dev zlib1g-dev libunwind-dev uuid-dev

    - name: Build and install submodules
      run: >-
           git submodule update --init
           && (cd asteria && ./makedeb.sh && sudo dpkg -i *.deb)
           && (cd http-parser && ./makedeb.sh && sudo dpkg -i *.deb)
           && (cd taxon && ./makedeb.sh && sudo dpkg -i *.deb)

    - name: Install dependencies
      run: >-
           sudo apt-get install -y lib{mysqlclient,mongoc,hiredis}-dev

    - name: Configure
      run: >-
           meson setup -Denable-debug-checks=true -Doptimization=1 build_ci

    - name: Build
      run: meson compile -Cbuild_ci

    - name: Run tests (full)
      run: meson test -Cbuild_ci --print-errorlogs
